twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Shared/Port/Frontend/Twig/Templates': 'shared'
        'src/Post/Port/Frontend/Twig/Templates': 'post'

when@test:
    twig:
        strict_variables: true
