services:
  php:
    build:
      dockerfile: internal/php/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/var/www/project

  db:
    image: mysql:8.4.0
    ports:
        - "3306:3306"
    volumes:
      - ./var/database:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: development
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lps
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project
      - ./internal/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: lps