services:
  php:
    build:
      dockerfile: internal/php/Dockerfile
    expose:
      - 9000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/var/www/project

  db:
    image: postgres:16.2
    ports:
        - "5432:5432"
    volumes:
      - ./var/database:/var/lib/postgresql/data:rw
    restart: always # always restart unless stopped manually
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: lps

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project
      - ./internal/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: lps