services:
  php:
    build:
      dockerfile: internal/php/Dockerfile
    expose:
      - 9000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/var/www/project

  db:
    image: mysql:8.4.0
    ports:
        - "3306:3306"
    volumes:
      - ./var/database:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: development
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lps

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project
      - ./internal/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: lps