services:
  nginx:
    platform: linux/amd64

  db:
    platform: linux/amd64
    volumes:
      - db:/var/lib/mysql:rw

  kafka:
    volumes:
      - kafka:/bitnami/kafka

  rabbitMq:
    volumes:
      - rabbitMq:/var/lib/rabbitmq/mnesia/

volumes:
  db:
  kafka:
  rabbitMq:
