# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  ssh:
    cmds:
      - docker compose exec -it php bash

  code-quality:
    desc: 'Execute all code quality checks'
    cmds:
      - task: phpcbf
      - task: psalm

  phpcs:
    cmds:
      - docker compose exec php php vendor/bin/php-cs-fixer fix -vvv

  psalm:
    cmds:
      - docker compose exec php php vendor/bin/psalm

  protobuf:
    cmds:
      - docker compose exec php protoc --php_out=gprotobuf src/Shared/Port/Gprotobuf/post.proto

  tests-unit:
    cmds:
      - docker compose exec php php vendor/bin/phpunit --testdox tests/Unit

  tests-integration:
    cmds:
      - docker compose exec php php vendor/bin/phpunit --testdox tests/Integration

  tests:
    desc: 'Execute all tests'
    cmds:
      - task: tests-unit
      - task: tests-integration
