# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  ssh:
    cmds:
      - docker compose exec -it php bash

  code-quality:
    desc: 'Execute all code quality checks'
    cmds:
      - task: phpcbf
      - task: psalm

  phpcs:
    cmds:
      - docker compose exec php php vendor/bin/php-cs-fixer fix -vvv

  psalm:
    cmds:
      - docker compose exec php php vendor/bin/psalm
