services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Shared\Port\Bus\Query\SymfonyQueryBus:
    arguments:
      $messageBus: '@query.bus'

  App\Shared\Port\Bus\Command\SymfonyCommandBus:
    arguments:
      $messageBus: '@command.bus'