controllers_shared_frontend:
  resource:
    path: ../src/Shared/Port/Frontend/Controller/
    namespace: App\Shared\Port\Frontend\Controller
  type: attribute

controllers_post_frontend:
    resource:
        path: ../src/Post/Port/Frontend/Controller/
        namespace: App\Post\Port\Frontend\Controller
    type: attribute

controllers_post_api:
  resource:
    path: ../src/Post/Port/Api/Controller/
    namespace: App\Post\Port\Api\Controller
  type: attribute
