name: Validate Coding Standards

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PHPCS
        run: php vendor/bin/phpcs -p src tests