name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  code-standard:
    uses: ./.github/workflows/coding_standards.yml
  unit-tests:
    uses: ./.github/workflows/tests-unit.yml
  integration-tests:
    uses: ./.github/workflows/tests-integration.yml