name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pre Build
        run: cp internal/php/custom.php.ini.dist internal/php/custom.php.ini

      - name: Build docker images
        run: docker compose build

      - name: Start docker images
        run: docker compose up -d php --wait

      - name: Install Dependencies
        run: docker compose exec -it php composer install

      - name: Build Cache
        run: docker compose exec -it php php bin/console cache:clear --env=test

      - name: Run Unit Tests
        run: docker compose exec -it php php bin/phpunit --testdox tests/Unit

      - name: Stop docker images
        run: docker compose down
