name: Run Unit Tests

on:
  workflow_call:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Pre Build # Image should be created and pushed before any other workflow and then be re-used
        run: |
          cp internal/php/custom.php.ini.dist internal/php/custom.php.ini
          cp .env.test .env

      - name: Build docker images
        run: docker compose build

      - name: Start docker images
        run: docker compose up -d php --wait

      - name: Install Dependencies
        run: docker compose exec -it php composer install

      - name: Build Cache
        run: docker compose exec -it php php bin/console cache:clear --env=test

      - name: Run Unit Tests
        run: task tests-unit

      - name: Stop docker images
        run: docker compose down
